### ISSUE TITLE
Error displaying ROI in the 'ROI refinement' module

### ISSUE THREAD

**Issue by DZneuro** [porteralab/EZcalcium#1]
Hi! When I was trying to load the .mat file in the ROI refinement module, here pops up the following error. 
"Warning: Image is too big to fit on screen; displaying at 50% 
> In images.internal.initSize (line 71)
  In truesize (line 48)
  In ez_roi_refine>load_ROI_Callback (line 380)
  In gui_mainfcn (line 95)
  In ez_roi_refine (line 42)
  In matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)ez_roi_refine('load_ROI_Callback',hObject,eventdata,guidata(hObject)) 
Error using reshape
To RESHAPE the number of elements must not change.

Error in ez_roi_refine>view_ROI_function (line 566)
    single_ROI = full(reshape(handles.ROI.A_or(:,ROI_number),map_size(1),map_size(2)));

Error in ez_roi_refine>load_ROI_Callback (line 471)
    view_ROI_function(hObject, eventdata, handles) %Automatically load first ROI

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in ez_roi_refine (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)ez_roi_refine('load_ROI_Callback',hObject,eventdata,guidata(hObject))
 
Error while evaluating UIControl Callback."

I can see the whole field of view and traces in the GUI, but the enlarged view of the current ROI is black and the currently selected ROI is not highlighted in black. I am wondering how shall I fix it? 
Thanks for the help!

**Comment by bodayw** [comment]
Hi,

What is the frame resolution of your image file?

**Comment by DZneuro** [comment]
Thank you so much for getting back. The frame resolution is 2448x1600
pixels and I converted to 8 bit images. Is it causing the problem?

Thanks,
Dawei
：

**Comment by bodayw** [comment]
It should be fixed now. Feel free to reopen if you still have issues.

**Comment by DZneuro** [comment]
Hi bodayw,

Thanks a lot for the help, however, the problem seem still persists. I am using 2048 by 2048 image this time. And got the same error in the reshape process. Please see below.

Warning: Image is too big to fit on screen; displaying at 33% 
> In images.internal.initSize (line 71)
  In truesize (line 48)
  In ez_roi_refine>load_ROI_Callback (line 380)
  In gui_mainfcn (line 95)
  In ez_roi_refine (line 42)
  In matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)ez_roi_refine('load_ROI_Callback',hObject,eventdata,guidata(hObject)) 
Error using reshape
To RESHAPE the number of elements must not change.

Error in ez_roi_refine>view_ROI_function (line 566)
    single_ROI = full(reshape(handles.ROI.A_or(:,ROI_number),map_size(1),map_size(2)));

Error in ez_roi_refine>load_ROI_Callback (line 471)
    view_ROI_function(hObject, eventdata, handles) %Automatically load first ROI

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in ez_roi_refine (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)ez_roi_refine('load_ROI_Callback',hObject,eventdata,guidata(hObject))
 
Error while evaluating UIControl Callback.

Error using reshape
To RESHAPE the number of elements must not change.

Error in ez_roi_refine>view_ROI_function (line 566)
    single_ROI = full(reshape(handles.ROI.A_or(:,ROI_number),map_size(1),map_size(2)));

Error in ez_roi_refine>ROI_list_Callback (line 480)
view_ROI_function(hObject, eventdata, handles)

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in ez_roi_refine (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)ez_roi_refine('ROI_list_Callback',hObject,eventdata,guidata(hObject))
 
Error while evaluating UIControl Callback.

**Comment by bodayw** [comment]
Hi,

It appears that you're still using the old version.

Maybe it's because you're using the custom MATLAB toolbox here?
https://github.com/porteralab/EZcalcium/releases

If so, it wouldn't work as I haven't updated the release version yet. For now, please download the source code files manually. For this particular fix, only one file was changed:
https://github.com/porteralab/EZcalcium/blob/master/ez_roi_refine.m
So you can just download this file and replace the one on your MATLAB PATH.

**Comment by DZneuro** [comment]
Got it! It's working great now! Thanks!

**Comment by maverle** [comment]
Hi there,

 I was wondering what frame resolution you would recommend using? I'm imaging with a very small GRIN lens (0.5 mm in diameter) for deep imaging in the central amygdala. 
My avi videos are currently 480-by-752  16-bit. 
I'm very new to calcium analyses and would appreciate any help or tips. 

Best, 

Maarten
