### ISSUE TITLE
motion correction

### ISSUE THREAD

**Issue by CAPTAIN1218** [porteralab/EZcalcium#10]
hi ,is there anyone could explain why i get this message?   thanks.

Analyzing and transferring files to the workers ...done.
Error using parallel.FevalFuture/fetchNext
The function evaluation completed with an error.

Error in normcorre_batch_even (line 258)
            [idx, shifts_temp, Mf_temp] = fetchNext(future_results);

Error in ez_motion_correction/RunMotionCorrectionButtonPushed (line 275)
                [~, ~, template, options_mc] = normcorre_batch_even(filename, options);

Caused by:
    Error using register_frame (line 6)
    Undefined function 'split_frame' for input arguments of type 'single'.
 
Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback (line 386)
Error while evaluating Button PrivateButtonPushedFcn.

**Comment by bodayw** [comment]
Looks like you didn't have EZcalcium properly installed, so that MATLAB couldn't find the function 'split_frame' which is part of the NoRMCorre package. Please try following exactly the installation instructions.
