### ISSUE TITLE
Unrecognized field name "Z_mod".

### ISSUE THREAD

**Issue by snorlaxchoi** [porteralab/EZcalcium#11]
Hi, 

I have encountered a problem while running roi refinement, can someone help me out with this issue?

Thanks!

Unrecognized field name "Z_mod".

Error in ez_roi_refine/view_roi (line 305)
            plot(app.RawUIAxes, app.roidata.Z_mod(cur_roi, :))

Error in ez_roi_refine/ROIListBoxValueChanged (line 718)
            view_roi(app)
 
Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback (line 470)
Error while evaluating ListBox PrivateValueChangedFcn.

Unrecognized function or variable 'frames'.

Error in ez_roi_refine/calc_roidata (line 238)
                app.roiref.baseline_window = floor(frames * baseline_loc);

Error in ez_roi_refine/LoadDataButtonPushed (line 679)
            calc_roidata(app)
 
Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback (line 427)
Error while evaluating Button PrivateButtonPushedFcn.

**Comment by bodayw** [comment]
Thanks for reporting this. Turned out it was a stupid typo...

Now fixed in the new release:
https://github.com/porteralab/EZcalcium/releases/tag/v2.1.3
