### ISSUE TITLE
Unrecognized function or variable 'find_unsaturatedPixels'.

### ISSUE THREAD

**Issue by Lifei7** [porteralab/EZcalcium#14]
when I tried to do a automated ROI detection, the program shows an error as follows:

"Unrecognized function or variable 'find_unsaturatedPixels'.

Error in preprocess_data (line 70)
P.pixels = find_unsaturatedPixels(Y);                % pixels that do not exhibit saturation

Error in ez_roi_detect/RunROIDetectionButtonPushed (line 365)
                [P, Y] = preprocess_data(Y, p, options);

Error in matlab.apps.AppBase>@(source,event)executeCallback(appdesigner.internal.service.AppManagementService.instance(),app,callback,requiresEventData,event) (line 63)
            newCallback = @(source, event)executeCallback(appdesigner.internal.service.AppManagementService.instance(), ...
 
Error while evaluating Button PrivateButtonPushedFcn."

Is this because my file has something that is not compatible with this analysis? What should I do to solve this?

**Comment by bodayw** [comment]
The error message indicates that the `find_unsaturatedPixels` function, a function of CaImAn, cannot be found. 

Make sure you follow the instructions carefully while installing EZcalcium.

Closing for now.
