### ISSUE TITLE
Error using register_frame

### ISSUE THREAD

**Issue by egarciaclave** [porteralab/EZcalcium#19]
Hi, 

I just dowloaded EZcalcium and I'm trying to see how it works. I am not a really Matlab person. 
I'm using a 16-bit TIFF file previously converted from a .oir file. There is only 1 channel with 1500 frames.
The following errors appeared when applying the Motion Correction:

Error using parallel.FevalFuture/fetchNext
The function evaluation completed with an error.

Error in normcorre_batch_even (line 258)
            [idx, shifts_temp, Mf_temp] = fetchNext(future_results);

Error in ez_motion_correction/RunMotionCorrectionButtonPushed (line 275)
                [~, ~, template, options_mc] = normcorre_batch_even(filename, options);

Error in appdesigner.internal.service.AppManagementService/executeCallback (line 171)
                callback(appOrUserComponent, event);

Error in matlab.apps.AppBase>@(source,event)executeCallback(ams,app,callback,requiresEventData,event) (line 62)
            newCallback = @(source, event)executeCallback(ams, ...

Caused by:
    Error using register_frame
    Undefined function 'imwarp' for input arguments of type 'single'.
 
Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback
Error while evaluating Button PrivateButtonPushedFcn.

Could you please tell me how to fix this errors?
Thank you in advance!

Elena

**Comment by bodayw** [comment]
Hi Elena,

It looks like you may not have the Image Processing Toolbox installed, which is required by EZcalcium.
