### ISSUE TITLE
Input and output question

### ISSUE THREAD

**Issue by charlesphi** [porteralab/EZcalcium#2]
Thank you very much for this very intuitive software I love it!

I am wondering if there is a way to register my image using a red non functional channel acquired in parralel to the calcium Imaging (my cells express gcamp amd td-tomato). My calcium signal is really dim during baseline and I  am not sure it can be used for registration.

In the output I would like to make sure which signal is actually the raw deltaF/F0. is it the F_raw?

Thank you

**Comment by bodayw** [comment]
Hi,

I'm glad that you like it!

> I am wondering if there is a way to register my image using a red non functional channel acquired in parralel to the calcium Imaging

EZcalcium doesn't support this at the moment, but it should be possible if you use NoRMCorre directly. The idea is pretty straightforward - first run motion correction on the red channel, and apply the shifts for each frame (and in case you use non-rigid motion correction, for each patches on each frame) to the green channel instead. You will need to dig a bit into the NoRMCorre code to see how this is done.

> My calcium signal is really dim during baseline and I am not sure it can be used for registration.

I would just give it a try first and see.

> In the output I would like to make sure which signal is actually the raw deltaF/F0. is it the F_raw?

The `F_raw` is called "raw" in a sense to compare with `F_inferred`: `F_inferred` are traces that fitted with estimated calcium dynamics, while `F_raw` makes no dynamics assumptions. However, according to CaImAn, `F_raw` (and `F_inferred`) already have other overlapping ROIs and background subtracted, so `F_raw` is not the "raw" trace you will get by directly extracting average pixel values from the raw images.
