### ISSUE TITLE
ROI detection, find_unsaturatedPixels error

### ISSUE THREAD

**Issue by bendbir** [porteralab/EZcalcium#20]
This seems like a great tool, especially for ROI detection.  I've just begun trying to use it after installation of toolboxes and ran into an unexpected error message with the first AVI file I tried to load (see command window report below).  The AVI input file is greyscale single channel, saved in Fiji from an image sequence of TIFF files.

Which component uses "find_unsaturatedPixels", and what might be going wrong?

________________________________________________________________________

_Starting ROI detection for C:\Users\bdoyle\OneDrive - Biogen\Desktop\2wk_Neuroburst_CoCulture_Well__D_007\New_Channel_0.avi
Unrecognized function or variable 'find_unsaturatedPixels'.

Error in preprocess_data (line 70)
P.pixels = find_unsaturatedPixels(Y);                % pixels that do not exhibit saturation

Error in ez_roi_detect/RunROIDetectionButtonPushed (line 365)
                [P, Y] = preprocess_data(Y, p, options);

Error in matlab.apps.AppBase>@(source,event)executeCallback(appdesigner.internal.service.AppManagementService.instance(),app,callback,requiresEventData,event) (line 63)
            newCallback = @(source, event)executeCallback(appdesigner.internal.service.AppManagementService.instance(), ...
 
Error while evaluating Button PrivateButtonPushedFcn._

**Comment by bodayw** [comment]
Hi,

It looks like you did not install EZcalcium properly such that some subfolders of EZcalcium are not added into MATLAB PATH. Please follow the installation instructions exactly, and make sure to use "Add with Subfolders..." when adding folders to PATH.
