### ISSUE TITLE
Error when using MCEM and MCMC

### ISSUE THREAD

**Issue by ghost** [porteralab/EZcalcium#22]
Hello,

I have a small problem with the ROI Detection. When I use the deconvolution method MCEM (CVX and SPGL1), I get the error message << Unrecognized function or variable 'P_merged'>>.

Furthemore, when the method MCMC is selected I end up with <<All of the input arguments must be of the same size and shape.
Previous inputs had size 1 in dimension 1. Input #3 has size 79>>

Cheers,

Antoine

**Comment by bodayw** [comment]
Should be all fixed now in [v3.0.2](https://github.com/porteralab/EZcalcium/releases/tag/v3.0.2).
