### ISSUE TITLE
Errors during ROI detection

### ISSUE THREAD

**Issue by Neuropharmacist** [porteralab/EZcalcium#25]
I'm encountering multiple errors (first two appear to be Out of Memory), and the third (Error using classify_comp_corr
Array construction from ByteBuffer Threw an exception).

The file I'm trying to analyze is is a 5,4GB tif with 22000 frames. I have a power desktop with 64GB RAM. Are these memory issues still something that should be expected?

Any advice on how to proceed with files like this? Should I divide the stack into multiple files and run ROI detection for those, and then use the ROI matching feature? It is important for me to keep track which neurons are active during various stages of the time-series.

----- ERROR 1

Starting ROI detection for D:\x\M5testavi_mcor.tif
Estimating the noise power for each pixel from a simple PSD estimate...  done 
No spatial downsampling is performed. Consider spatial downsampling if the field of view is very large. 
starting resampling 
Initializing components with greedy method 
found 10 out of 200 neurons..
found 20 out of 200 neurons..
found 30 out of 200 neurons..
found 40 out of 200 neurons..
found 50 out of 200 neurons..
found 60 out of 200 neurons..
found 70 out of 200 neurons..
found 80 out of 200 neurons..
found 90 out of 200 neurons..
found 100 out of 200 neurons..
found 110 out of 200 neurons..
found 120 out of 200 neurons..
found 130 out of 200 neurons..
found 140 out of 200 neurons..
found 150 out of 200 neurons..
found 160 out of 200 neurons..
found 170 out of 200 neurons..
found 180 out of 200 neurons..
found 190 out of 200 neurons..
found 200 out of 200 neurons..
Refining initial estimates with HALS...Starting parallel pool (parpool) using the 'Processes' profile ...
Connected to the parallel pool (number of workers: 12).
  done 
Updated spatial components 
146 out of 200 components updated 
194 out of 200 components updated 
199 out of 200 components updated 
200 out of 200 components updated 
146 out of 200 components updated 
194 out of 200 components updated 
199 out of 200 components updated 
200 out of 200 components updated 
Error using classify_comp_corr
Out of Memory during deserialization

Error in ez_roi_detect/RunROIDetectionButtonPushed (line 391)
                    rval_space = classify_comp_corr(Y, A, C, b, f, options);

Error in appdesigner.internal.service.AppManagementService/executeCallback (line 171)
                callback(appOrUserComponent, event);

Error in matlab.apps.AppBase>@(source,event)executeCallback(ams,app,callback,requiresEventData,event) (line 62)
            newCallback = @(source, event)executeCallback(ams, ...
 
Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback
Error while evaluating Button PrivateButtonPushedFcn.

----- ERROR 2

Warning: File: update_temporal_components.m Line: 234 Column: 40
The temporary variable 'model_ar' will be cleared at the beginning of each iteration of the parfor-loop. If 'model_ar' is used before it is set, a runtime error will occur. For more information, see Parallel for Loops in MATLAB,
"Uninitialized Temporaries". 
147 out of 200 components updated 
194 out of 200 components updated 
200 out of 200 components updated 
147 out of 200 components updated 
194 out of 200 components updated 
200 out of 200 components updated 
Warning: A worker aborted during execution of the parfor loop. The parfor loop will now run again on the remaining workers. 
Warning: A worker aborted during execution of the parfor loop. The parfor loop will now run again on the remaining workers. 
Error using parallel.internal.pool.serialize
Out of Memory during serialization

Error in distcomp.remoteparfor/serialize (line 280)
            data = parallel.internal.pool.serialize(...

Error in distcomp.remoteparfor/buildParforController (line 162)
                serializedInitData = obj.serialize(obj.InitData, initDataBufSize);

Error in distcomp.remoteparfor/rebuildParforController (line 190)
                obj.buildParforController();

Error in distcomp.remoteparfor/handleIntervalErrorResult (line 259)
                obj.rebuildParforController();

Error in distcomp.remoteparfor/getCompleteIntervals (line 396)
                            [r, err] = obj.handleIntervalErrorResult(r);

Error in classify_comp_corr (line 116)
    parfor i = 1:K_m

Error in ez_roi_detect/RunROIDetectionButtonPushed (line 391)
                    rval_space = classify_comp_corr(Y, A, C, b, f, options);

Error in appdesigner.internal.service.AppManagementService/executeCallback (line 171)
                callback(appOrUserComponent, event);

Error in matlab.apps.AppBase>@(source,event)executeCallback(ams,app,callback,requiresEventData,event) (line 62)
            newCallback = @(source, event)executeCallback(ams, ...
 
Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback
Error while evaluating Button PrivateButtonPushedFcn.

----- ERROR 3

>> ezcalcium
Starting ROI detection for D:\x\M5testavi_mcor.tif
Estimating the noise power for each pixel from a simple PSD estimate...  done 
No spatial downsampling is performed. Consider spatial downsampling if the field of view is very large. 
starting resampling 
Initializing components with greedy method 
found 10 out of 200 neurons..
found 20 out of 200 neurons..
found 30 out of 200 neurons..
found 40 out of 200 neurons..
found 50 out of 200 neurons..
found 60 out of 200 neurons..
found 70 out of 200 neurons..
found 80 out of 200 neurons..
found 90 out of 200 neurons..
found 100 out of 200 neurons..
found 110 out of 200 neurons..
found 120 out of 200 neurons..
found 130 out of 200 neurons..
found 140 out of 200 neurons..
found 150 out of 200 neurons..
found 160 out of 200 neurons..
found 170 out of 200 neurons..
found 180 out of 200 neurons..
found 190 out of 200 neurons..
found 200 out of 200 neurons..
Refining initial estimates with HALS...Starting parallel pool (parpool) using the 'Processes' profile ...
Connected to the parallel pool (number of workers: 12).
  done 
Updated spatial components 
Warning: File: update_temporal_components.m Line: 234 Column: 40
The temporary variable 'model_ar' will be cleared at the beginning of each iteration of the parfor-loop. If 'model_ar' is used before it is set, a runtime error will
occur. For more information, see Parallel for Loops in MATLAB, "Uninitialized Temporaries". 
147 out of 200 components updated 
194 out of 200 components updated 
200 out of 200 components updated 
147 out of 200 components updated 
194 out of 200 components updated 
200 out of 200 components updated 
Error using classify_comp_corr
Array construction from ByteBuffer Threw an exception.

Error in ez_roi_detect/RunROIDetectionButtonPushed (line 391)
                    rval_space = classify_comp_corr(Y, A, C, b, f, options);

Error in appdesigner.internal.service.AppManagementService/executeCallback (line 171)
                callback(appOrUserComponent, event);

Error in matlab.apps.AppBase>@(source,event)executeCallback(ams,app,callback,requiresEventData,event) (line 62)
            newCallback = @(source, event)executeCallback(ams, ...
 
Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback
Error while evaluating Button PrivateButtonPushedFcn.

IdleTimeout has been reached.
Parallel pool using the 'Processes' profile is shutting down.

**Comment by gulcanakgul** [comment]
Hi, I am having similar issues. How did you solve these errors below? Thanks!

 
Error in ez_roi_detect/RunROIDetectionButtonPushed (line 391)
rval_space = classify_comp_corr(Y, A, C, b, f, options);

Error in appdesigner.internal.service.AppManagementService/executeCallback (line 171)
callback(appOrUserComponent, event);

Error in matlab.apps.AppBase>@(source,event)executeCallback(ams,app,callback,requiresEventData,event) (line 62)
newCallback = @(source, event)executeCallback(ams, ...

Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback
Error while evaluating Button PrivateButtonPushedFcn.
