### ISSUE TITLE
problem running EZcalcium 

### ISSUE THREAD

**Issue by hsangom** [porteralab/EZcalcium#27]
Hello, 

When I click Run ROI Detection I get this:

Undefined function 'strel' for input arguments of type 'char'.

Error in CNMFSetParms (line 301)
    {strel('disk',1,0)}

Error in ez_roi_detect/RunROIDetectionButtonPushed (line 344)
                options = CNMFSetParms(...                           % Check CNMFSetParms.m for more details
 
Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback (line 335)
Error while evaluating Button PrivateButtonPushedFcn.

Then I tried to install the Image Processing Toolbox, as I have seen in other thread but a message pops up saying:

Error 339: Your MathWorks account login session has expired. 

But I am actually logged in to the mathworks page.

Thanks,

Helena

**Comment by bodayw** [comment]
Hello,

`strel` is indeed a function from the Image Processing Toolbox that is necessary here.

Maybe try logging in again? Or just contact the provider of your MATLAB license to troubleshoot the issue.
