### ISSUE TITLE
issue with GUI and getRunningApp

### ISSUE THREAD

**Issue by mp599** [porteralab/EZcalcium#3]
Hi, I have read the paper and it seems like a great toolbox.
Wanted to try but have some trouble. I have Matlab 2018a for MacOS, I have all 4 required packaged installed and installed (with path and all) EZcalcium, CaImAn, and NoRMCorre.
Still there is something I am missing. the command ezcalcium opens the first GUI, but then only the help button works, all others give me some trouble with 'getRunningApp'. Below is the error. Any idea?

cheers, 

Marco

**Undefined function 'getRunningApp' for input arguments of type
'ez_motion_correction'.

Error in ez_motion_correction (line 663)
            runningApp = getRunningApp(app);

Error in ezcalcium/MotionCorrectionButtonPushed (line 22)
            ez_motion_correction
 
Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback (line 309)
Error while evaluating Button PrivateButtonPushedFcn.**

**Comment by bodayw** [comment]
Hi,

Yes, this is a known issue. The `getRunningApp` is a new function introduced in recent versions of MATLAB (either 2020a or 2020b, not sure). I was using 2020b when building these apps with MATLAB App Designer, so they are not compatible with older versions of MATLAB. I had to update the README to reflect this change, see a26d82e.

Upgrade MATLAB to 2020b (or later) should fix this issue.
