### ISSUE TITLE
Frame warning

### ISSUE THREAD

**Issue by jaesungle** [porteralab/EZcalcium#8]
Hi, thanks for amazing and helpful app
I have frame problem in ROI refinement step.

Warning window says 'baseline window has too many frames to fit in baseline location. setting baseline window to maximum possible value as fallback' 

how can i set baseline window value..?

**Comment by snorlaxchoi** [comment]
Hi, I ran into the same issue.
I'm wondering whether you've solved this?

**Comment by bodayw** [comment]
This is explained in the documentation (Wiki and in-app help button).
