### ISSUE TITLE
File size issue ROI detection

### ISSUE THREAD

**Issue by Lilian-E** [porteralab/EZcalcium#9]
Hi all,

Thanks for creating this useful toolbox. I have a 15 min two-photon recording and had no issues going through the motion correction, but did encounter an issue with the ROI detection. The motion corrected tiff file is 5.38 GB and contains 22,007 8-bit tiff images, but for some reason the code turns it into a 21.5 GB file when trying to run the ROI detection. 

My RAM is 16 GB (at least 3x as large as the file I am working with) but of course if the file becomes 21 GB during the ROI detection processing step, my RAM memory is not big enough. 

See below for the error message in Matlab:
>> ezcalcium
Starting ROI detection for C:\Users\Lilian Emming\Desktop\avi 4254\video_42554_mcor.tif
Requested 512x512x22007 (21.5GB) array exceeds maximum array size preference (15.8GB). This might cause MATLAB to become unresponsive.

Error in ez_roi_detect/RunROIDetectionButtonPushed (line 338)
                if ~isa(Y, 'single'); Y = single(Y); end % convert to single

Related documentation
 
Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback (line 410)
Error while evaluating Button PrivateButtonPushedFcn.

Any ideas why the file becomes 4x as large during this step?

Thanks!

Lilian

**Comment by bodayw** [comment]
Yes this is expected. As you see in the error message, the ROI detection converts the input data to single precision (32-bit) which is exactly 4 times your original bit-depth (8-bit).

Unfortunately this is a requirement of CaImAn as of now.
